-- Seed reference content. Projects are inserted as technically reviewed and
-- published only where source material has been confirmed by the company.
DELETE FROM project_media;
DELETE FROM projects;
DELETE FROM articles;

INSERT INTO projects (title, slug, theme, county, locality, client_category, plant_type, capacity_m3,
  feedstocks, applications, completion_date, project_status, summary, challenge, site_conditions,
  feedstock_assessment, energy_demand, engineering_response, construction_sequence, gas_handling,
  appliance_connections, slurry_management, commissioning, outcomes, media_rights_status,
  technical_review_status, workflow_state, published_at)
VALUES
('Kerarapon 16 m³ system', 'kerarapon-16m3-system', 'One plant. Multiple productive uses.', 'Kajiado', 'Kerarapon',
 'farm', 'fixed_dome', 16,
 '["Cow manure","Food waste"]', '["Cooking","Baking","Water heating","Electricity","Chaff cutting"]',
 '2023', 'completed',
 'A 16 m³ fixed-dome plant feeding a household kitchen, an oven, a water heater, a generator and a chaff cutter from a single digester.',
 'The homestead was buying cooking fuel while manure accumulated on site and required disposal.',
 'Gently sloping ground with firm soil, adequate space downslope of the cattle boma and a short carrying distance to the kitchen.',
 'Daily cattle manure supplemented with kitchen waste, mixed with water at approximately 1:1 by volume before feeding.',
 'Family cooking, baking, hot water and intermittent mechanical loads for fodder chopping.',
 'A fixed-dome digester with an expansion chamber, sized for the measured daily manure load and the combined appliance demand.',
 'Setting out, excavation, foundation, dome masonry, gas-tight plastering, inlet and outlet construction, backfilling and pipe installation.',
 'Dome take-off to a main valve, condensate trap at the pipeline low point, H2S filter before the engine, and a manometer for operator pressure checks.',
 'Household cooker, oven, water heater, generator and converted chaff-cutter engine on a branched low-pressure network.',
 'Digested slurry overflows to a lined store and is applied to fodder and vegetable plots.',
 'Charged with manure and water, leak tested, first gas flared, then appliances commissioned and the operator trained.',
 '[{"claim":"Household cooking fuel purchases reduced","evidence":"Client-reported"},{"claim":"Plant operating on daily manure feeding","evidence":"Company site observation"}]',
 'company_owned', 'approved', 'published', now()),

('Gataka 12 m³ poultry and pig-waste system', 'gataka-12m3-poultry-pig-system', 'Two livestock waste streams. One circular farm system.',
 'Kiambu', 'Gataka', 'farm', 'fixed_dome', 12,
 '["Poultry waste","Pig manure"]', '["Cooking","Brooding","Water pumping","Bio-slurry recovery"]',
 '2023', 'completed',
 'Poultry and pig waste converge into one digestion process serving the farm kitchen, the brooder and slurry recovery.',
 'Two separate waste streams created odour and disposal costs, while brooding relied on purchased fuel.',
 'Farm yard with sufficient area between the piggery and the poultry units, requiring careful drainage design.',
 'Poultry litter is energy rich but high in nitrogen, so it is co-digested with pig manure to keep digestion stable.',
 'Cooking for the farm household, chick brooding heat and occasional water pumping.',
 'A 12 m³ fixed-dome plant with a combined mixing tank and controlled loading to avoid ammonia inhibition.',
 'Excavation, dome construction, dual inlet arrangement, plastering and gas testing.',
 'Condensate trap and filtration ahead of the brooder line, with isolation valves at each branch.',
 'Farm cooker, poultry brooder and a converted pump engine.',
 'Slurry is stored and applied to farm plots, reducing fertiliser purchases.',
 'Charged, leak tested and handed over with feeding and safety training.',
 '[{"claim":"Both waste streams now handled on site","evidence":"Company site observation"},{"claim":"Brooding heat supplied by biogas","evidence":"Client-reported"}]',
 'company_owned', 'approved', 'published', now()),

('Ammodump Kwenia Eco Lodge 8 m³ and 12 m³ phases', 'kwenia-eco-lodge-phases', 'A system trusted enough to expand.',
 'Kajiado', 'Kwenia', 'commercial', 'fixed_dome', 12,
 '["Food waste","Cow manure"]', '["Cooking","Water heating","Lighting"]',
 '2024', 'completed',
 'An initial 8 m³ plant proved reliable at the lodge and was followed by a second 12 m³ phase as demand grew.',
 'A remote eco lodge needed cooking energy and hot water without depending on delivered fuel.',
 'Remote site with limited road access and careful placement required to protect the surrounding landscape.',
 'Kitchen waste from the lodge combined with manure available nearby.',
 'Guest and staff cooking, hot water and evening lighting.',
 'Phase one delivered an 8 m³ digester; phase two added a 12 m³ digester on the proven layout.',
 'Excavation, masonry, plastering, gas testing and pipe routing to the kitchen block.',
 'Filtration and condensate management sized for the longer pipe run to the kitchen.',
 'Commercial cooker, water heater and biogas lamps.',
 'Slurry stored and used on the grounds.',
 'Both phases charged, tested and commissioned with staff training.',
 '[{"claim":"Second phase commissioned after the first performed as expected","evidence":"Company records"}]',
 'company_owned', 'approved', 'published', now()),

('Nairobi school 32 m³ project', 'nairobi-school-32m3-project', 'Institutional-scale energy and waste management.',
 'Nairobi', 'Nairobi', 'institutional', 'fixed_dome', 32,
 '["Food waste","Human waste"]', '["Cooking","Water heating"]',
 '2024', 'completed',
 'A 32 m³ institutional plant treating daily kitchen and sanitation waste while supplying the school kitchen.',
 'A large daily waste load and high cooking-fuel expenditure in a constrained urban compound.',
 'Urban compound with limited free area, requiring compact layout and protection of drainage.',
 'Kitchen waste from daily meal preparation combined with sanitation flow from the school.',
 'Bulk cooking for the student population and hot water for the kitchen.',
 'A 32 m³ digester with an expansion chamber and a gas network reaching the kitchen block.',
 'Excavation, reinforced construction, plastering, gas-tightness testing and pipe installation.',
 'Main valve, condensate trap, filtration and pressure control before the institutional burners.',
 'Commercial cookers and a water heater.',
 'Effluent managed in line with institutional sanitation requirements.',
 'Charged, tested and commissioned with kitchen-staff training.',
 '[{"claim":"Daily kitchen and sanitation waste treated on site","evidence":"Company site observation"}]',
 'company_owned', 'approved', 'published', now()),

('Slaughterhouse feasibility study', 'slaughterhouse-feasibility-study', 'Managing difficult organic waste through engineered treatment.',
 'Nairobi', 'Nairobi', 'commercial', 'study', NULL,
 '["Slaughterhouse waste","Wastewater"]', '["Wastewater treatment","Electricity"]',
 '2024', 'study_completed',
 'A feasibility study assessing rumen content, blood and washdown effluent for engineered anaerobic treatment.',
 'High-strength organic effluent creating compliance risk and disposal cost.',
 'Constrained industrial yard with existing drainage that must be separated from the treatment line.',
 'Rumen content, blood and washdown water measured over the operating week, with strong daily variation.',
 'Potential to offset thermal energy and generate electricity if gas is filtered.',
 'Recommended pre-treatment, screening and a staged anaerobic process with an effluent compliance plan.',
 'Not applicable  -  study phase only.',
 'Filtration and moisture removal identified as mandatory before any engine use.',
 'Not applicable  -  study phase only.',
 'Effluent handling and discharge compliance assessed against regulatory requirements.',
 'Not applicable  -  study phase only.',
 '[{"claim":"Waste volumes characterised across an operating week","evidence":"Company measurement"},{"claim":"Energy recovery potential identified","evidence":"Company estimate"}]',
 'company_owned', 'approved', 'published', now());

INSERT INTO articles (slug, title, excerpt, body, workflow_state, published_at) VALUES
('how-anaerobic-digestion-works', 'How anaerobic digestion works',
 'Four bacterial stages turn organic waste into methane-rich biogas.',
 E'Anaerobic digestion happens without oxygen. Hydrolysis breaks complex material into simpler compounds, acidogenesis and acetogenesis convert those into acids and acetate, and methanogens finally produce methane and carbon dioxide.\n\nStability depends on temperature, consistent feeding and the absence of soap, disinfectant, sand and plastic in the feed.',
 'published', now()),
('sizing-a-biogas-plant', 'Sizing a biogas plant honestly',
 'Why no capacity can be quoted before a site survey.',
 E'Sizing begins with a measured daily waste quantity, not a guess. From there, the slurry volume, retention time and gas storage requirement follow.\n\nEnergy demand matters just as much: a plant that produces enough gas but cannot deliver it at the required pressure will disappoint the user. Both sides of the calculation must be measured on site.',
 'published', now());
